# HaiNan API DOC

# Group 會員
HanNan Chance

::: note
## 文件說明

使用第三方登入 - Facebook

+ 會員
    + 第三方登入 [GET]

:::

## 第三方登入 request [/api/beach/login/facebook]

### 第三方登入 [GET] 

example: https://hainan-api.oss.tw/api/beach/login/facebook

---

+ Response 200

    + Headers

            x-access-token: "token值"

# Group 淨灘資料

::: note
## 文件說明

API

+ 淨灘資料
    + 提取淨灘資料 [GET]

:::

## 提取淨灘資料 request [/api/beach]

### 提取淨灘資料 [GET] 

example: https://hainan-api.oss.tw/api/beach

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | id | 區域id | int | 
 2 | city | 城市 | string |
 3 | beachName | 海灘名稱 | string |
 4 | title | 海灘區段 | string | 
 5 | description | 區域描述 | string |
 6 | geojson | geo格式圖資 | string | 
 7 | ref_url | 參考連結網址 | string |
 8 | beachClean | 淨灘需求 | boolean | false: 沒需求, true: 有需求
 9 | auther | 通報建立者 | string | 
 10 | editor | 通報修改者 | string |
 11 | createDate | 通報建立時間 | string |
 12 | updateDate | 通報修改時間 | string |

+ Response 200

    + Body

            {
                "result": 
                    [
                        {
                            "id": "6227cdd6-271b-4e16-92aa-78698c734b63",
                            "city": "新北市",
                            "beachName": "嘉寶沙灘",
                            "title": "嘉寶沙灘-1",
                            "description": "",
                            "geojson": [
                                [
                                    121.32094860076906,
                                    25.123298323905402
                                ],
                                [
                                    121.32587934324003,
                                    25.123774144896046
                                ]
                            ],
                            "refURL": "https://ecolife2.epa.gov.tw/coastal/SeaResult.aspx?slid=118",
                            "beachClean": false,
                            "auther": "fd6e1fc0-e116-44c8-8bda-5de78e48568b",
                            "createDate": "2018-01-30T10:40:28.000Z",
                            "editor": "fd6e1fc0-e116-44c8-8bda-5de78e48568b",
                            "updateDate": "2018-01-30T10:40:28.000Z"
                        },
                        ...
                    ]
            }

# Group 通報
HanNan Chance

::: note
## 文件說明

API

+ 通報
    + 提取淨灘通報 [GET]
    + 建立淨灘通報 [POST] - 需token
    + 修改淨灘通報 [PUT] - 需token
    + 刪除淨灘通報 [DELETE] - 需token

:::

## 淨灘通報 request [/api/beach/notification]

### 提取淨灘通報 [GET] 

example: https://hainan-api.oss.tw/api/beach/notification

---



`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | id | 淨灘通報id | int | 
 2 | targetID | 淨灘id | int | 
 3 | targetName | 淨灘地點 | string |
 4 | description | 描述 | string |
 5 | imageURL | 通報圖片 | string |
 6 | beachClean | 淨灘需求 | boolean | false: 沒需求, true: 有需求
 7 | auther | 通報建立者 | string |
 8 | editor | 通報修改者 | string |
 9 | createDate | 通報建立時間 | string |
 10 | updateDate | 通報修改時間 | string |

+ Response 200

    + Body

            {
                "result": 
                    [
                        {
                            "id": 1,
                            "targetID": 2,
                            "targetName": "黃金海岸",
                            "description": "黃金海岸需要淨灘",
                            "imageURL": "https://i.imgur.com/FZIV7sy.jpg",
                            "beachClean": true,
                            "auther": "王小明",
                            "editor": "陳大明",
                            "createDate": "2018-01-01",
                            "updateData": "2018-01-15"
                        },
                        ...
                    ]
            }

### 建立淨灘通報 [POST] 

example: https://hainan-api.oss.tw/api/beach/notification

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | targetID | 淨灘id | int | (必填欄位)
 2 | description | 描述 | string | 
 3 | imageURL | 通報圖片 | string | (必填欄位)
 4 | beachClean | 淨灘需求 | boolean | false: 沒需求, true: 有需求 | (必填欄位)

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘通報成功！",
                        "createData": 
                            {
                                "targetID": 2,
                                "description": "黃金海岸需要淨灘",
                                "imageURL": "https://i.imgur.com/FZIV7sy.jpg",
                                "beachClean": true
                            }
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘通報失敗！",
                        "err": "請輸入 [:必填欄位] 值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘通報失敗！",
                        "err": "請輸入正確的token。"
                    }
            }

## 淨灘通報 request [/api/beach/notification/{id}]

+ Parameters

    + id: `1` (required, int) - 淨灘通報id

### 修改淨灘通報 [PUT] 

example: https://hainan-api.oss.tw/api/beach/notification/?id=1

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | id | 淨灘通報id | int | (必填欄位)
 2 | description | 描述 | string |
 3 | imageURL | 通報圖片 | string | 
 4 | beachClean | 淨灘需求 | boolean | false: 沒需求, true: 有需求 |

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘通報成功！",
                        "updateData": 
                            {
                                "id": 1,
                                "description": "黃金海岸不需要淨灘",
                                "imageURL": "https://i.imgur.com/FZIV7sy.jpg",
                                "beachClean": false
                            }
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘通報失敗！",
                        "err": "請輸入id值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘通報失敗！",
                        "err": "請輸入正確的token。"
                    }
            }

### 刪除淨灘通報 [DELETE] 

example: https://hainan-api.oss.tw/api/beach/notification/?id=1

---

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘通報成功！",
                        "deleteID": 1
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘通報失敗！",
                        "err": "請輸入id值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘通報失敗！",
                        "err": "請輸入正確的token。"
                    }
            }

# Group 活動

::: note
## 文件說明

API 

+ 活動
    + 提取淨灘活動 [GET]
    + 建立淨灘活動 [POST] - 需token
    + 修改淨灘活動 [PUT] - 需token
    + 刪除淨灘活動 [DELETE] - 需token

:::

## 淨灘活動 request [/api/beach/activity]

### 提取淨灘活動 [GET] 

example: https://hainan-api.oss.tw/api/beach/activity

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | id | 淨灘活動id | int | 
 2 | targetID | 淨灘id | int | 
 3 | targetName | 海灘名稱 | string |
 4 | title | 淨灘活動標題 | string |
 5 | description | 活動描述 | string |
 6 | contact | 聯絡資訊 | string | 電話
 7 | dateTime | 活動時間 | string |
 8 | place | 集合地點 | string |
 9 | refURL | 外部參考網址 | string |
 10 | auther | 活動建立者 | string |
 11 | editor | 活動修改者 | string |
 12 | createDate | 通報建立時間 | string |
 13 | updateDate | 通報修改時間 | string |

+ Response 200

    + Body

            {
                "result": 
                    [
                        {
                            "id": 1,
                            "targetID": 2,
                            "targetName": "黃金海岸",
                            "title": "快來撿垃圾。",
                            "description": "黃金海岸需要淨灘",
                            "contact": "0911111111",
                            "dateTime": "2018-02-01",
                            "place": "台南市安平區123號",
                            "refURL": "https://ecolife2.epa.gov.tw/coastal/",
                            "auther": "王小明",
                            "editor": "陳大明",
                            "createDate": "2018-01-01",
                            "updateData": "2018-01-15"
                        },
                        ...
                    ]
            }

### 建立淨灘活動 [POST] 

example: https://hainan-api.oss.tw/api/beach/activity

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | targetID | 淨灘id | int | (必填欄位)
 2 | title | 淨灘活動標題 | string | (必填欄位)
 3 | description | 活動描述 | string | (必填欄位)
 4 | contact | 聯絡資訊 | string | 電話 (必填欄位)
 5 | dateTime | 活動時間 | string | (必填欄位)
 6 | place | 集合地點 | string | (必填欄位)
 7 | refURL | 外部參考網址 | string |

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘活動成功！",
                        "createData": 
                            {
                                "targetID": 2,
                                "title": "快來撿垃圾。",
                                "description": "黃金海岸需要淨灘",
                                "contact": "0911111111",
                                "dateTime": "2018-02-01",
                                "place": "台南市安平區123號",
                                "refURL": "https://ecolife2.epa.gov.tw/coastal/"
                            }
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘活動失敗！",
                        "err": "請輸入 [:必填欄位] 值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "建立淨灘活動失敗！",
                        "err": "請輸入正確的token。"
                    }
            }

## 淨灘活動 request [/api/beach/activity/{id}]

+ Parameters

    + id: `1` (required, int) - 淨灘活動id

### 更改淨灘活動 [PUT] 

example: https://hainan-api.oss.tw/api/beach/activity/?id=1

---

`參數說明`

編號 | 欄位名稱 | 內容 | 註記
--:| ---- | ----------- | ---- |
 1 | targetID | 淨灘id | int | (必填欄位)
 2 | title | 淨灘活動標題 | string |
 3 | description | 活動描述 | string |
 4 | contact | 聯絡資訊 | string | 電話
 5 | dateTime | 活動時間 | string |
 6 | place | 集合地點 | string |
 7 | refURL | 外部參考網址 | string |

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘活動成功！",
                        "updateData": 
                            {
                                "targetID": 2,
                                "title": "黃金海岸",
                                "description": "黃金海岸需要淨灘",
                                "contact": "0911111111",
                                "dateTime": "2018-02-01",
                                "place": "台南市安平區123號",
                                "refURL": "https://ecolife2.epa.gov.tw/coastal/"
                            }
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘活動失敗！",
                        "err": "請輸入id值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "更改淨灘活動失敗！",
                        "err": "請輸入正確的token。"
                    }
            }

### 刪除淨灘活動 [DELETE] 

---

example: https://hainan-api.oss.tw/api/beach/activity/?id=1

+ Response 200

    + Headers

            x-access-token: "token值"

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘活動成功！",
                        "deleteID": 1 
                    }
            }

+ Response 400

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘活動失敗！",
                        "err": "請輸入id值。"
                    }
            }

+ Response 403

    + Body

            {
                "result": 
                    {
                        "state": "刪除淨灘活動失敗！",
                        "err": "請輸入正確的token。"
                    }
            }